### ISSUE TITLE
Multipath Model Based on Nginx QUIC

### ISSUE THREAD

**Issue by nandsky** [quicwg/multipath#281] opened 2023-10-26 11:41 UTC
I have tried to implement the 05 version of the multipath draft based on nginx quic. The model diagram is as follows, and if there are any errors, please let me know.

![mpquic](https://github.com/quicwg/multipath/assets/10154791/41088be1-38e1-4904-a58e-9a4712297382)

annotations:
1. This model is based on NGINX QUIC implementation, with the following mapping relationship:
  a. QUIC SM: ngx_quic_connection_t
  b. socket: ngx_quic_socket_t
  c. path: ngx_quic_path_t
  d. send_ctx: ngx_quic_send_ctx_t
  e. recv_ctx: splits from ngx_quic_send_ctx
2. This model splits 4-tuple into serverCID-bound RX and clientCID-bound TX, which generally differ in number.

Actually  i have already described this model in https://github.com/quicwg/multipath/issues/270.  I am opening a new issue because the draft's definition of "path" is not clear. Additionally, I hope to use this model to discuss interoperability with other implementations.

**Comment by mirjak** [comment] 2023-11-03 15:15
closing as this is a duplicate of #270

**Closed by mirjak** 2023-11-03 15:15 UTC
