### ISSUE TITLE
Discussion: Remove ACK_MP frame from draft-ietf-quic-multipath ？

### ISSUE THREAD

**Issue by iyangsj** [quicwg/multipath#271] opened 2023-09-05 11:41 UTC
Briefly, the argument is as follows：
- The ACP_MP frame is not essential for multipath transport.
- Adding ACK_MP raises several design and implementation issues that need to be more thoroughly investigated.

Perhaps a better approach would be to follow the KISS principle：
- Use the ACK frame to acknowledge the received packets, which should be sent on the same path（Similar to the MPTCP).
- However, we do not prevent future extensions from defining ACK_MP, and using it requires negotiation.

**Comment by LPardue** [comment] 2023-09-05 14:19
Seems like a dupe of https://github.com/quicwg/multipath/issues/181, which was closed. Have you got any additional points that were not already addressed there?

**Comment by iyangsj** [comment] 2023-09-06 12:05
@LPardue Thank you for such helpful information. 
It is challenging to achieve a simpler and more elegant solution without making some trade-offs on requirements and suitable changes to conceptual models.
I would like to provide a detailed description later.

**Comment by LPardue** [comment] 2023-09-06 12:32
Got it. To be clear, since #181 is now resolved it reflects the established consensus of the group. Therefore, the bar to reconsidering that consensus and making any changes is going to be higher. We'd be looking for convincing new arguments in a timely manner in order to revisit this matter.

**Comment by mirjak** [comment] 2023-11-03 15:12
In issue #181 it was already decided that it is better to be explicit and use ACK_MP. This also enables sending ACK over different paths which is seem as a feature, e.g. always using the lowest latency path. I don't see any new issue or concern raised here. Therefore I propose to close this issue with no action.

**Comment by iyangsj** [comment] 2023-11-03 16:33
>In issue https://github.com/quicwg/multipath/issues/181 it was already decided that it is better to be explicit and use ACK_MP. This also enables sending ACK over different paths which is seem as a feature, e.g. always using the lowest latency path.

The existing design choice for ACK_MP is rooted in the per-path-per-pns model. Under this model, it seems there's no better design than what we currently have.


>  I don't see any new issue or concern raised here.

The present solution introduces unnecessary issues, such as ACK ambiguity, RTT estimation, large deviation from QUIC. Even worse, some algorithms that rely on ACK from the same path might not perform well. 

If we properly design the conceptual model, we can find a simpler and more feasible design that avoids these extra problems.

**Comment by iyangsj** [comment] 2023-11-06 07:44
_CASE B:_

![CASE B](https://github.com/quicwg/multipath/assets/780807/dad0b805-e44f-4848-8046-fd9c54836736)

- The Sender uses the COPA algorithm for both path A and path B.
- The Receiver replies ACK frames only on path A.

> The simplest implementation is to compute smoothedRTT and RTTvar per [Section 5.3](https://rfc-editor.org/rfc/rfc9002#section-5.3) of [[QUIC-RECOVERY](https://www.rfc-editor.org/rfc/rfc9002)] regardless of the path through which MP_ACKs are received. This algorithm will provide good results, except if the set of paths changes and the ACK_MP sender revisits its sending preferences.

- When path A is congested, `BBR B` may inaccurately estimate the queue delay for path B and improperly decrease the sending rate.

**Comment by mirjak** [comment] 2024-07-09 09:45
Consideration for ACK scheduling and impact on congestion control is discussed in [6.3. ](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#section-6.3)[Computing Path RTT](https://quicwg.org/multipath/draft-ietf-quic-multipath.html#name-computing-path-rtt). Further issue #77 notes that it might be useful for a future extension to provide guidance on ACK scheduling (frequency as well as which path to use). However, it was decided that this can be left as an extension. Therefore I'm closing this issue now. Thanks for the detailed discussion!

**Closed by mirjak** 2024-07-09 09:45 UTC
Labels: duplicate, no-action-needed
