### ISSUE TITLE
consider allowing sending on a new path optimistically

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/multipath#206] opened 2023-03-31 02:25 UTC
The draft currently forbids sending non-probing frames before path validation has completed:
> If validation succeed, the client can send non-probing, 1-RTT packets on the new paths.

While this is a sane thing to do in many cases, there might be good reasons to optimistically send non-probing frames right away. This is forbidden in RFC 9000 because sending non-probing frames abandons the original path, but this problem doesn't exist when doing multipath.

Of course, if the path doesn't work, this means that those packets will be lost and data might need to be retransmitted, but that's a risk the client might be willing to take under certain circumstances.

**Comment by huitema** [comment] 2023-04-03 04:31
This is the same text as RFC 9000, and its validation requirement.

In theory, nothing "really bad" will happen if a node starts sending packets on a path without waiting for the validation. The main risk is that the packets will be lost, which is a bummer for the sender but also a risk that the sender can calculate. There is however a security consideration: if the node could be tricked towards sending packet to an unsuspecting target, enabling use in DDOS.

This could happen for example:

* if a malicious server sends the DOS target addresses in the "preferred address" parameter. 
* if a client sends a probe and fakes the source address of the DOS target.

In the first case, the client should definitely not use the path learned from the server before validation.
In the second case, the server should definitely not use the path learned from the client before validation.

**Comment by marten-seemann** [comment] 2023-04-03 05:05
These DoS concerns could be mitigated by limiting the amount of data sent on an unverified path, as RFC 9000 already does with the amplification limit. Packets containing a PATH_CHALLENGE frame need to be padded to at 1200 bytes anyway, so this is already quite similar to the situation during the handshake.

I can think of many situations where sending 3 MTUs worth of application data is a lot better than not sending anything.

**Comment by huitema** [comment] 2023-04-03 05:17
Actually, all that is already addressed in RFC 9000 [9.3. ](https://www.rfc-editor.org/rfc/rfc9000.html#section-9.3)[Responding to Connection Migration](https://www.rfc-editor.org/rfc/rfc9000.html#name-responding-to-connection-mi): "An endpoint MAY send data to an unvalidated peer address, but it MUST protect against potential attacks as described in Sections [9.3.1](https://www.rfc-editor.org/rfc/rfc9000.html#address-spoofing) and [9.3.2](https://www.rfc-editor.org/rfc/rfc9000.html#on-path-spoofing). An endpoint MAY skip validation of a peer address if that address has been seen recently. In particular, if an endpoint returns to a previously validated path after detecting some form of spurious migration, skipping address validation and restoring loss detection and congestion state can reduce the performance impact of the attack."

It would make a lot of sense to just insert an explanation that for multipath, an endpoint may send data before on a path before full validation, with a pointer to the text in RFC 9000.

**Comment by mirjak** [comment] 2023-06-30 12:06
I think the draft does actually not explicitly forbid this. The sentences cited above just says that you can send non-probing packets after validation but it doesn't restrict what you can do before validation. If that is covered in RFC9000 we should probably just add a pointer somewhere.

Also note that this is basically a duplicate of issue #50 which has some additional discussion.

**Closed** 2023-10-22 10:56 UTC
Labels: duplicate, has PR
