### ISSUE TITLE
Is the Path Status number space per-path or global?

### ISSUE THREAD

**Issue by MikeBishop** [quicwg/multipath#348] opened 2024-05-25 03:51 UTC
It appears that the Path Status sequence number is always interpreted in the context of a path ID. However, I did not find an explicit statement of whether the same sequence number for different paths is permitted or prohibited.

**Comment by mirjak** [comment] 2024-05-27 12:20
currently it's one sequence number space for the whole connection. So, no the same seq number is not permitted. However, we the explicit oath id approach we could reconsider that. In any case we need to clarify it. However, I will close this now as this is a duplicate of issue #312

**Closed by mirjak** 2024-05-27 12:20 UTC
Labels: duplicate
