### ISSUE TITLE
Are we sure we really don't need stand-by?

### ISSUE THREAD

**Issue by mirjak** [quicwg/multipath#22] opened 2021-10-18 07:56 UTC
I believe stand-by (or backup) has been useful in MPTCP. This is not really about scheduling because all it says is: I won't use this path actively(yet)  but please leave it open.

**Comment by mirjak** [comment] 2022-01-11 12:30
Do we need any more text in the draft or can we just close this issue?

**Comment by qdeconinck** [comment] 2022-01-11 15:07
The current text in Section 3.2.3 ("To avoid idle timeout of a path, endpoints can send ack-eliciting packets such as packets containing PING frames Section 19.2 of [QUIC-TRANSPORT] on that path to keep it alive. Sending periodic PING frames also helps prevent middlebox timeout, as discussed in Section 10.1.2 of [QUIC-TRANSPORT].") is fine for me.

**Comment by huitema** [comment] 2022-01-11 21:25
I don't see many QUIC applications relying on keep-alive. For example, when studying DNS over QUIC, we concluded that it was much easier to use resumption and 0-RTT than to try to keep the paths open through NAT. I also think the issue is asymmetric:

* Servers have no good way to know that a path that has been idle for some time is still valid. The client might have moved, or the NAT binding might have changed. If servers send traffic on an idle path, there is a high risk that the traffic will be lost. The default should be, "silent close on idle".

* Clients typically do not have such limitations, because their traffic will force a new NAT binding if one is missing.

There are mitigating strategies, such as only sending redundant traffic on suspect paths, but we probably don't need to discuss that here.

**Comment by mirjak** [comment] 2022-01-12 09:23
QUIC applications rely less on keep-alive (as you have 0-RTT resumption), however, I think the situation is different for multipath. If you have multiple paths available, you might still decide to only send data on one path at a time, e.g. you want to have a hot stand-by, meaning you already open a new path but didn't decide to use it yet, or want to be able to switch back to an "old" path anytime.

**Comment by mirjak** [comment] 2022-03-03 13:39
Do we need further text here or can we close this issue?

**Comment by mirjak** [comment] 2022-03-05 14:34
Actually thinking about this further I still think we should have at least one signal  to tell the other end that a path should not be used.

This is the typical handover case: a client opens both a wifi and a cellular path, also sends keep-alive on the cellular path to make sure one can switch over quickly. However, when it requests data from the server, the server doesn't know which path to use or that it should actually not use one of path as it is more costly. Therefore I think we need a signal to tell the _other end_ that a path should not actively be used for sending data (as long as another path is still available).

**Comment by yfmascgy** [comment] 2022-03-06 07:45
@mirjak  I agree that having a signal for stand-by is beneficial. Actually, we did have the standy-by signal with the PATH_STATUS frame in draft-liu. The PATH_STATUS frame signals three status: (1) abandon, (2) stand-by, and (3) available. 
     PATH_STATUS Frame {
       Type (i) = TBD-03 (experiments use 0xbaba03),
       Path Identifier (..),
       Path Status sequence number (i),
       Path Status (i),
       Path Priority (i),
     }
When the three drafts were merged, the PATH_STATUS frame was replaced by the current PATH_ABANDON frame, as at that time we wanted the first version to focus on the very basic features. I think we can put the stand-by status back if it proves to be a general requirement.

**Comment by Yanmei-Liu** [comment] 2022-03-10 05:53
The stand-by status in draft-liu is used to explicitly inform the sender not to schedule packets on this path, but endpoints can keep the path context not to be removed. Once the endpoints need to use this path again, they can send PATH_STATUS(active) to update the status, and send packets on the path immediately without path validation and other preparation for this path.

We can discuss about whether if we need to add the mechanism into the working group version.

**Comment by mirjak** [comment] 2022-03-23 14:38
At IETF-113 there was general support for this idea. Next step: write PR

**Comment by mirjak** [comment] 2022-04-06 10:07
The PATH_STATUS frame as described in PR#117 is a rather generic way to update path information. Actually not sure if we need this at this point. I was assuming that indicating a path to be a stand-by or back-up path is a rather static information. E.g. if your mobile link is more expensive, this is static and will not change over the life time of the path. As such another option would be to signal this information during path initiation, e.g. creating an MP_PATH_CHALLANGE frame that contains a flag.

**Comment by huitema** [comment] 2022-04-07 00:47
It is generally preferred to defined composable frames, rather than create a special purpose version of an existing frame. I would combine Status & Challenge in a single message rather than modifying challenge. But we have to understand what happens if a challenge is lost, repeated, etc.

I am also not sure that the 'status' is "once and forever". I could see the status evolving over time, and alternating between standby and available. But we need to add a bit to the specification. In particular:

* is there a default status when no status frame have been received on a path?
* does the status change if the peer starts sending non-probing frames on the path?
* can both client and server change the status of a path?
* do frames affect both directions of a path?

**Comment by mirjak** [comment] 2022-04-07 08:33
> is there a default status when no status frame have been received on a path?

Yes, available. However, I wouldn't really call this a default status, because this info is a signal to the other end in order to give a recommendation if that should be sent on this path or not, but the fine sending decision is a local decision. If this info is not available, the sender has to base its decision on other (local known) criteria. 

> does the status change if the peer starts sending non-probing frames on the path?

No.

> can both client and server change the status of a path?

Yes and no. The status tells the other end if or if not it should send data on the path. So effectively it impacts only one direction of the path as the other direction is a local decision.

> do frames affect both directions of a path?

No. As I just said. This is a recommendation for the sender, however, if the sender follows that recommendation is effectively also a local decision.

Again, I think we should at this point really just focus on the standby function and not make this too generic because that makes is more complicated.

**Comment by huitema** [comment] 2022-04-07 19:55
@mirjak the current default status is "standby until the client has sent non probing frames, available after that" -- per RFC 9000. I would think that the client sending a status frame overrides that, since "status" is not "probing", but it is probably worth specifying.

Similarly, I do agree with the "unilateral" view of status that you are presenting, "just tell the other end whether to send on that path of not." But it is worth specifying.

**Comment by mirjak** [comment] 2022-07-06 13:58
Okay, if we agree that we want a separate PATH_STATUS frame then I think PR #117 is ready to merge. @huitema and @qdeconinck can you review and approve PR #117 ? Thanks!

**Closed** 2022-07-11 12:19 UTC
Labels: has PR, design, needs-discussion
